/* The service definition for bomtastic, generated by role.
 *
 *   yeet run services/conf.js -- --role node                        | yeet service import - -j --now
 *   yeet run services/conf.js -- --role hub --node 10.0.0.2:3450 | yeet service import - -j --now
 *
 * A node runs the app's isolate as a lazy unit and serves its tty at
 * /app on the gateway; `yeetkit start --isolate ws://127.0.0.1:3450/app`
 * dials it instead of spawning its own. The hub is a node too, plus one
 * proxy route per `--node host:port`, so its manifest lists every
 * machine's /app and the fleet page can walk it.
 */
const role = yeet.args.role ?? "node";
const port = Number(yeet.args.port ?? 3450);
const dir = yeet.args.dir ?? ".";

const service = {
  alias: yeet.args.alias ?? `bom-${role}`,
  restart: "always",
  enabled: true,
  units: {
    app: { isolate: `${dir}/dist/server.js`, lazy: true },
    gateway: {
      "web-server": `ws://0.0.0.0:${port}/`,
      routes: {
        "/app": { target: "app", portal: "tty", description: "bomtastic isolate" },
        "/console": { target: "app", portal: "console", description: "bomtastic isolate logs" },
      },
    },
  },
};

if (role === "hub") {
  for (const node of [].concat(yeet.args.node ?? [])) {
    const host = node.split(":")[0].replaceAll(".", "-");
    service.units.gateway.routes[`/nodes/${host}`] = {
      upstream: `ws://${node}/`,
      description: `bomtastic on ${node}`,
    };
  }
}

console.log(JSON.stringify(service, null, 2));
